/*
 * E-fulfilment Shop API
 *
 * The E-fulfilment Shop API allows you to integrate your service with our warehouse.
 *
 * API version: 1.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package efulfillmentshop

import (
	"encoding/json"
)

// SaleWrite Sale entity
type SaleWrite struct {
	// The sale carrier ID
	CarrierId *int32 `json:"carrierId,omitempty"`
	// The sale channel
	ChannelId int32 `json:"channelId"`
	// The sale channel reference
	ChannelReference string `json:"channelReference"`
	// The sale invoice address ID
	InvoiceAddressId int32 `json:"invoiceAddressId"`
	// The sale shipping address ID
	ShippingAddressId int32 `json:"shippingAddressId"`
}

// NewSaleWrite instantiates a new SaleWrite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSaleWrite(channelId int32, channelReference string, invoiceAddressId int32, shippingAddressId int32, ) *SaleWrite {
	this := SaleWrite{}
	this.ChannelId = channelId
	this.ChannelReference = channelReference
	this.InvoiceAddressId = invoiceAddressId
	this.ShippingAddressId = shippingAddressId
	return &this
}

// NewSaleWriteWithDefaults instantiates a new SaleWrite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSaleWriteWithDefaults() *SaleWrite {
	this := SaleWrite{}
	return &this
}

// GetCarrierId returns the CarrierId field value if set, zero value otherwise.
func (o *SaleWrite) GetCarrierId() int32 {
	if o == nil || o.CarrierId == nil {
		var ret int32
		return ret
	}
	return *o.CarrierId
}

// GetCarrierIdOk returns a tuple with the CarrierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SaleWrite) GetCarrierIdOk() (*int32, bool) {
	if o == nil || o.CarrierId == nil {
		return nil, false
	}
	return o.CarrierId, true
}

// HasCarrierId returns a boolean if a field has been set.
func (o *SaleWrite) HasCarrierId() bool {
	if o != nil && o.CarrierId != nil {
		return true
	}

	return false
}

// SetCarrierId gets a reference to the given int32 and assigns it to the CarrierId field.
func (o *SaleWrite) SetCarrierId(v int32) {
	o.CarrierId = &v
}

// GetChannelId returns the ChannelId field value
func (o *SaleWrite) GetChannelId() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *SaleWrite) GetChannelIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *SaleWrite) SetChannelId(v int32) {
	o.ChannelId = v
}

// GetChannelReference returns the ChannelReference field value
func (o *SaleWrite) GetChannelReference() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ChannelReference
}

// GetChannelReferenceOk returns a tuple with the ChannelReference field value
// and a boolean to check if the value has been set.
func (o *SaleWrite) GetChannelReferenceOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ChannelReference, true
}

// SetChannelReference sets field value
func (o *SaleWrite) SetChannelReference(v string) {
	o.ChannelReference = v
}

// GetInvoiceAddressId returns the InvoiceAddressId field value
func (o *SaleWrite) GetInvoiceAddressId() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.InvoiceAddressId
}

// GetInvoiceAddressIdOk returns a tuple with the InvoiceAddressId field value
// and a boolean to check if the value has been set.
func (o *SaleWrite) GetInvoiceAddressIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.InvoiceAddressId, true
}

// SetInvoiceAddressId sets field value
func (o *SaleWrite) SetInvoiceAddressId(v int32) {
	o.InvoiceAddressId = v
}

// GetShippingAddressId returns the ShippingAddressId field value
func (o *SaleWrite) GetShippingAddressId() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.ShippingAddressId
}

// GetShippingAddressIdOk returns a tuple with the ShippingAddressId field value
// and a boolean to check if the value has been set.
func (o *SaleWrite) GetShippingAddressIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ShippingAddressId, true
}

// SetShippingAddressId sets field value
func (o *SaleWrite) SetShippingAddressId(v int32) {
	o.ShippingAddressId = v
}

func (o SaleWrite) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CarrierId != nil {
		toSerialize["carrierId"] = o.CarrierId
	}
	if true {
		toSerialize["channelId"] = o.ChannelId
	}
	if true {
		toSerialize["channelReference"] = o.ChannelReference
	}
	if true {
		toSerialize["invoiceAddressId"] = o.InvoiceAddressId
	}
	if true {
		toSerialize["shippingAddressId"] = o.ShippingAddressId
	}
	return json.Marshal(toSerialize)
}

type NullableSaleWrite struct {
	value *SaleWrite
	isSet bool
}

func (v NullableSaleWrite) Get() *SaleWrite {
	return v.value
}

func (v *NullableSaleWrite) Set(val *SaleWrite) {
	v.value = val
	v.isSet = true
}

func (v NullableSaleWrite) IsSet() bool {
	return v.isSet
}

func (v *NullableSaleWrite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSaleWrite(val *SaleWrite) *NullableSaleWrite {
	return &NullableSaleWrite{value: val, isSet: true}
}

func (v NullableSaleWrite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSaleWrite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


