/*
 * E-fulfilment Shop API
 *
 * The E-fulfilment Shop API allows you to integrate your service with our warehouse.
 *
 * API version: 1.2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package efulfilmentshop

import (
	"encoding/json"
)

// InlineResponse401 struct for InlineResponse401
type InlineResponse401 struct {
	Code *int32 `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewInlineResponse401 instantiates a new InlineResponse401 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse401() *InlineResponse401 {
	this := InlineResponse401{}
	return &this
}

// NewInlineResponse401WithDefaults instantiates a new InlineResponse401 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse401WithDefaults() *InlineResponse401 {
	this := InlineResponse401{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *InlineResponse401) GetCode() int32 {
	if o == nil || o.Code == nil {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse401) GetCodeOk() (*int32, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *InlineResponse401) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *InlineResponse401) SetCode(v int32) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *InlineResponse401) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse401) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *InlineResponse401) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *InlineResponse401) SetMessage(v string) {
	o.Message = &v
}

func (o InlineResponse401) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse401 struct {
	value *InlineResponse401
	isSet bool
}

func (v NullableInlineResponse401) Get() *InlineResponse401 {
	return v.value
}

func (v *NullableInlineResponse401) Set(val *InlineResponse401) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse401) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse401) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse401(val *InlineResponse401) *NullableInlineResponse401 {
	return &NullableInlineResponse401{value: val, isSet: true}
}

func (v NullableInlineResponse401) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse401) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


