/*
 * E-fulfilment Shop API
 *
 * The E-fulfilment Shop API allows you to integrate your service with our warehouse.
 *
 * API version: 1.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package efulfillmentshop

import (
	"encoding/json"
	"time"
)

// PurchaseLineRead Purchase Line entity
type PurchaseLineRead struct {
	// The purchase line description
	Description string `json:"description"`
	// The purchase line ID
	Id *int32 `json:"id,omitempty"`
	// The purchase line planned delivery date
	PlannedDate *time.Time `json:"plannedDate,omitempty"`
	// The product ID
	ProductId int32 `json:"productId"`
	// The purchase ID
	PurchaseId int32 `json:"purchaseId"`
	// The purchase line quantity received
	QtyReceived *int32 `json:"qtyReceived,omitempty"`
	// The purchase line quantity
	Quantity int32 `json:"quantity"`
}

// NewPurchaseLineRead instantiates a new PurchaseLineRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurchaseLineRead(description string, productId int32, purchaseId int32, quantity int32, ) *PurchaseLineRead {
	this := PurchaseLineRead{}
	this.Description = description
	this.ProductId = productId
	this.PurchaseId = purchaseId
	this.Quantity = quantity
	return &this
}

// NewPurchaseLineReadWithDefaults instantiates a new PurchaseLineRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurchaseLineReadWithDefaults() *PurchaseLineRead {
	this := PurchaseLineRead{}
	return &this
}

// GetDescription returns the Description field value
func (o *PurchaseLineRead) GetDescription() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *PurchaseLineRead) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PurchaseLineRead) SetDescription(v string) {
	o.Description = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PurchaseLineRead) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseLineRead) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PurchaseLineRead) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *PurchaseLineRead) SetId(v int32) {
	o.Id = &v
}

// GetPlannedDate returns the PlannedDate field value if set, zero value otherwise.
func (o *PurchaseLineRead) GetPlannedDate() time.Time {
	if o == nil || o.PlannedDate == nil {
		var ret time.Time
		return ret
	}
	return *o.PlannedDate
}

// GetPlannedDateOk returns a tuple with the PlannedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseLineRead) GetPlannedDateOk() (*time.Time, bool) {
	if o == nil || o.PlannedDate == nil {
		return nil, false
	}
	return o.PlannedDate, true
}

// HasPlannedDate returns a boolean if a field has been set.
func (o *PurchaseLineRead) HasPlannedDate() bool {
	if o != nil && o.PlannedDate != nil {
		return true
	}

	return false
}

// SetPlannedDate gets a reference to the given time.Time and assigns it to the PlannedDate field.
func (o *PurchaseLineRead) SetPlannedDate(v time.Time) {
	o.PlannedDate = &v
}

// GetProductId returns the ProductId field value
func (o *PurchaseLineRead) GetProductId() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
func (o *PurchaseLineRead) GetProductIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ProductId, true
}

// SetProductId sets field value
func (o *PurchaseLineRead) SetProductId(v int32) {
	o.ProductId = v
}

// GetPurchaseId returns the PurchaseId field value
func (o *PurchaseLineRead) GetPurchaseId() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.PurchaseId
}

// GetPurchaseIdOk returns a tuple with the PurchaseId field value
// and a boolean to check if the value has been set.
func (o *PurchaseLineRead) GetPurchaseIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PurchaseId, true
}

// SetPurchaseId sets field value
func (o *PurchaseLineRead) SetPurchaseId(v int32) {
	o.PurchaseId = v
}

// GetQtyReceived returns the QtyReceived field value if set, zero value otherwise.
func (o *PurchaseLineRead) GetQtyReceived() int32 {
	if o == nil || o.QtyReceived == nil {
		var ret int32
		return ret
	}
	return *o.QtyReceived
}

// GetQtyReceivedOk returns a tuple with the QtyReceived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseLineRead) GetQtyReceivedOk() (*int32, bool) {
	if o == nil || o.QtyReceived == nil {
		return nil, false
	}
	return o.QtyReceived, true
}

// HasQtyReceived returns a boolean if a field has been set.
func (o *PurchaseLineRead) HasQtyReceived() bool {
	if o != nil && o.QtyReceived != nil {
		return true
	}

	return false
}

// SetQtyReceived gets a reference to the given int32 and assigns it to the QtyReceived field.
func (o *PurchaseLineRead) SetQtyReceived(v int32) {
	o.QtyReceived = &v
}

// GetQuantity returns the Quantity field value
func (o *PurchaseLineRead) GetQuantity() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *PurchaseLineRead) GetQuantityOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *PurchaseLineRead) SetQuantity(v int32) {
	o.Quantity = v
}

func (o PurchaseLineRead) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["description"] = o.Description
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.PlannedDate != nil {
		toSerialize["plannedDate"] = o.PlannedDate
	}
	if true {
		toSerialize["productId"] = o.ProductId
	}
	if true {
		toSerialize["purchaseId"] = o.PurchaseId
	}
	if o.QtyReceived != nil {
		toSerialize["qtyReceived"] = o.QtyReceived
	}
	if true {
		toSerialize["quantity"] = o.Quantity
	}
	return json.Marshal(toSerialize)
}

type NullablePurchaseLineRead struct {
	value *PurchaseLineRead
	isSet bool
}

func (v NullablePurchaseLineRead) Get() *PurchaseLineRead {
	return v.value
}

func (v *NullablePurchaseLineRead) Set(val *PurchaseLineRead) {
	v.value = val
	v.isSet = true
}

func (v NullablePurchaseLineRead) IsSet() bool {
	return v.isSet
}

func (v *NullablePurchaseLineRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurchaseLineRead(val *PurchaseLineRead) *NullablePurchaseLineRead {
	return &NullablePurchaseLineRead{value: val, isSet: true}
}

func (v NullablePurchaseLineRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurchaseLineRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


